### ISSUE TITLE
Any plans for QLora?

### ISSUE THREAD

**Issue by asmith26** [keras-team/keras-hub#1537]
Hi there! `keras-nlp` supports Lora, e.g. from https://ai.google.dev/gemma/docs/lora_tuning

```python
...
gemma_lm.backbone.enable_lora(rank=4)
...
```

Just wondering are there any plans to implement QLora finetuning, to help make finetuning even more accessible on smaller GPUs?
https://arxiv.org/abs/2305.14314
https://huggingface.co/blog/4bit-transformers-bitsandbytes

Many thanks for any help, and this lib!

**Comment by mattdangerw** [comment]
Yes actually! We are currently working or rolling out some support for quantization generally and quantize lora.

We will work on some actual docs for this soon, but for now you can check out the `qlora.py` in the description of this PR to see what we are working on -> https://github.com/keras-team/keras/pull/19356/

I believe the 4 bit normal float from the qlora paper is not currently available, but int8 quantized weights layered in with lora should be good to go.

Early days on the feature, so any feedback appreciated as we build it out.

**Comment by mattdangerw** [comment]
Guide on this incoming...

https://github.com/keras-team/keras-io/pull/1889

**Comment by Gopi-Uppari** [comment]
Hi @asmith26,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by asmith26** [comment]
Have got this working https://keras.io/examples/keras_recipes/parameter_efficient_finetuning_of_gemma_with_lora_and_qlora/#qlora-finetuning

Many thanks again!
