### ISSUE TITLE
add Segformer

### ISSUE THREAD

**Issue by divyashreepathihalli** [keras-team/keras-hub#1763]
This task is part of the KerasHub project ( Consolidating all of KerasCV and KerasNLP models in to one place)
Models from KerasCV will be added to KerasNLP in KerasNLP infrstructure style. The development is now under the `keras-hub` branch in KerasNLP - https://github.com/keras-team/keras-nlp/tree/keras-hub

Steps to complete this Task
- Source code : https://github.com/keras-team/keras-cv/tree/master/keras_cv/src/models/segmentation/segformer
- Destination : A model folder here https://github.com/keras-team/keras-nlp/tree/keras-hub/keras_nlp/src/models
- Example PR : https://github.com/keras-team/keras-nlp/pull/1737, please follow the style from here and take a look at the comments on the PR for any design clarifications
- copy the model over
- use KerasNLP test routines to update the tests
- for reformatting the code run `shell/api_gen.sh`, `shell/format.sh` and `shell/lint.sh`
- The backbone will be added as a model, any downstream task model will be under the same model folder.

Add either @divyashreepathihalli, @mattdangerw  or @SamanehSaadat for review of any PR.

**Comment by cosmo3769** [comment]
Hi @divyashreepathihalli, I would love to work on this. Please assign me. Thank you!

**Comment by divyashreepathihalli** [comment]
Thank you @cosmo3769!! I will mark this as WIP

**Comment by divyashreepathihalli** [comment]
@cosmo3769 any updates on this?

**Comment by cosmo3769** [comment]
@divyashreepathihalli I will raise a PR by Friday EOD.

**Comment by divyashreepathihalli** [comment]
Hi @cosmo3769, Thank you for your interesting in contributing to KerasHub! The original contributor of SegFormer might take this issue up.  Perhaps you could browse through the other open issues and see if there's anything else that catches your eye? We're always looking for contributors with your enthusiasm! Thanks again!

**Comment by DavidLandup0** [comment]
@cosmo3769 hey, just wanted to check if there are any updates? 
I could take it off your plate and shape up the PR tonight.

**Comment by cosmo3769** [comment]
@divyashreepathihalli Apologies for the delay! I got caught up with some other work.
@DavidLandup0 Please take over. Thank you!
