### ISSUE TITLE
add weights conversion script for MiT

### ISSUE THREAD

**Issue by divyashreepathihalli** [keras-team/keras-hub#1871]
TODO:

- [ ] add weights conversion script here - https://github.com/keras-team/keras-hub/tree/master/tools/checkpoint_conversion
- [ ] Verify output with real inputs
- [ ] provide a working colab demo

Example PR - https://github.com/keras-team/keras-hub/pull/1855.

**Comment by DavidLandup0** [comment]
Closed with #1893
