### ISSUE TITLE
add weights and conversion script for effecientnet

### ISSUE THREAD

**Issue by divyashreepathihalli** [keras-team/keras-hub#1876]
TODO:

- [ ] add weights conversion script here - https://github.com/keras-team/keras-hub/tree/master/tools/checkpoint_conversion
- [ ] Verify output with real inputs
- [ ] provide a working colab demo

Example PR - https://github.com/keras-team/keras-hub/pull/1855.

**Comment by vulkomilev** [comment]
I will take this task

**Comment by pkgoogle** [comment]
Actually this is done: https://github.com/keras-team/keras-hub/pull/1933
