### ISSUE TITLE
Add FLUX model to KerasHub

### ISSUE THREAD

**Issue by divyashreepathihalli** [keras-team/keras-hub#1956]

**Comment by vulkomilev** [comment]
I will commit to this issue but I will need a mentorship at some point

**Comment by vulkomilev** [comment]
Here to say that I am doing a progress . By the next week I will have results

**Comment by vulkomilev** [comment]
Here https://github.com/valkomilev/keras-hub/tree/flux_model

**Comment by divyashreepathihalli** [comment]
Hey @vulkomilev FLUX model has been added to KerasHub
