### ISSUE TITLE
When will SegFormer and MiT be available?

### ISSUE THREAD

**Issue by edge7** [keras-team/keras-hub#1994]
Hi,
I am trying to understand the situation a bit, I am fairly sure that one month ago I read a tutorial on the keras website showing how to use MiT backbone in a SegFormer for image segmentation.
Now am not able to find it anymore, probably because of Keras-Cv/Nlp --> Hub mapping.

I am not hugely expert in transformers for Computer Vision tasks, as I usually use CNN, but I wanted to try something else now.

At the minute there is nothing officially released here?

I just see MiT and SegFormer in the master branch but they have not been released.  
Thanks for the clarificaitons

**Comment by edge7** [comment]
I've installed the master branch and this works:

```
image_encoder = keras_hub.models.MiTBackbone.from_preset("mit_b1_ade20k_512", image_shape=(224, 224, 3))
backbone = keras_hub.models.SegFormerBackbone(image_encoder=image_encoder, projection_filters=256)
segformer = keras_hub.models.SegFormerImageSegmenter(backbone=backbone, num_classes=3)
```

**Comment by edge7** [comment]
Ok.
In the meantime, do you think that directly use the master branch is not particularly risky? At least to start testing it out

**Comment by mattdangerw** [comment]
> Ok. In the meantime, do you think that directly use the master branch is not particularly risky? At least to start testing it out

Not at all! Testing out via the master branch encouraged. `pip install git+https://github.com/keras-team/keras-hub` will build directly from master or `pip install keras-hub-nightly` for a nightly built package.

There might always be some changes before release.
