### ISSUE TITLE
Adding Installation Process in the README

### ISSUE THREAD

**Issue by aflah02** [keras-team/keras-hub#53]
I think it would be a good idea if we add how someone can use the repository currently (pre-release) on Google Colab or locally by cloning and pip installing it as a part of the README or an Installation.md type file

The instructions would be pretty much:

1) Clone the repository using `git clone https://github.com/keras-team/keras-nlp` or downloading it directly
2) Moving into the directory using a `cd` command - `cd keras-nlp`
3) Running `pip install` once inside the folder

This could be helpful for people who just which to quickly setup this library to try stuff out

**Comment by abheesht17** [comment]
https://github.com/keras-team/keras-nlp/blob/master/.github/CONTRIBUTING.md#setup-environment

**Comment by aflah02** [comment]
Thanks @abheesht17 I didn't see that it already exists
